version: '{version}'
branches:
  only:
  - master
  - v3
image: Visual Studio 2019
configuration: Release
platform: x64
clone_folder: c:\projects\uacme
build:
  project: Source/uacme.sln
  verbosity: normal
after_build:
  7z a uacme.zip Source\*\output\x64\Release\*.exe
artifacts:
  - path: uacme.zip
